replicaCount: 1

image:
  repository: ghcr.io/doanhnc/nestjs-app-code  # Thay USERNAME của bạn
  tag: "8c1bea4b29ef0ee550da0ac7d9074a3e85fe0a80"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 3000
