replicaCount: 1

image:
  repository: ghcr.io/doanhnc/nestjs-app-code  # Thay USERNAME của bạn
  tag: "1d22188cebd226e147670e8851fcae01796b78a1"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 3000
