replicaCount: 1

image:
  repository: ghcr.io/doanhnc/nestjs-app-code  # Thay USERNAME của bạn
  tag: "39f623c799cf51ad5bab7068f25c2579a9883e49"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 3000
